### ISSUE TITLE
Not clickable in some regions

### ISSUE THREAD

**Issue by WuerfelDev** [l3nn4rt/click-to-close-overview#1]
Some regions are not clickable, I marked them here:
![Screenshot from 2021-01-06 18-20-42](https://user-images.githubusercontent.com/12686819/103800915-49746200-504d-11eb-8a53-53e43bb16373.png)

When no window is open on that workspace, the left and top areas are clickable, just not with a window.

**Comment by l3nn4rt** [comment]
Click action is currently limited to `Main.overview.viewSelector`, but I plan to extend it to the whole overview soon

**Comment by l3nn4rt** [comment]
This is now solved for the workspaces page.
Still I can't figure out how to make the same to the apps page in a clean way.

Edit: the area under the workspace thumbnails (bottom right) you made transparent won't be clickable with latest version neither (and it probably never will).

**Comment by l3nn4rt** [comment]
Overview is closed when clicked in all those regions (except for the bottom right) since version 2.
