### ISSUE TITLE
Realize the same function for the program menu 'Show Applications'

### ISSUE THREAD

**Issue by ivanmood0** [l3nn4rt/click-to-close-overview#2]
Thank you for the wonderful extension. Could you realize the same function for the program menu 'Show Applications' (possibly with another extension)?

**Comment by l3nn4rt** [comment]
Hi! I don't understand what you mean. Maybe you'd like a click on the overview to open the apps page?

**Comment by ivanmood0** [comment]
> Hi! I don't understand what you mean. Maybe you'd like a click on the overview to open the apps page?

No, I meant:
![ubt](https://user-images.githubusercontent.com/79835684/111641573-f6194f80-8805-11eb-9a98-b88c9b6aa89f.png)

**Comment by l3nn4rt** [comment]
You are using Gnome 3.36 or lower, which has **two** separated app views, "Frequently used" and "All applications".
In Gnome 3.38 we have **a single** (re-arrangeable) app view.
This extension does support Gnome 3.38 only, and already does what you are asking.

I have no time ATM to support older Gnome versions. If you want to contribute, please consider opening a pull request: I'll be very happy to merge it

**Comment by l3nn4rt** [comment]
Closing, since GS < 3.38 was never supported.
Also support to GS < 40 is dropped since 94d2037091b294d1c276bd8d37d499d0c0b47a33.
