### ISSUE TITLE
Improve interaction with Desktop Cube

### ISSUE THREAD

**Issue by FelixFourcolor** [l3nn4rt/click-to-close-overview#3]
[Desktop Cube](https://github.com/Schneegans/Desktop-Cube) allows you to click and drag the overview to switch workspaces. Currently, this extension takes away that feature of Desktop Cube, because clicking always closes the overview.

I don't know how they did it, but [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel) solves the problem. The extension has a setting `Behavior > Overview > Click empty space to close overview`, which if enabled, does what it says but still lets you interact with Desktop Cube normally.

Can you checkout how they did it and bring it to your extension?

**Comment by l3nn4rt** [comment]
Starting with version 10, it should work with Desktop Cube :)

**Comment by FelixFourcolor** [comment]
Confirm it works. Thank you!
