### ISSUE TITLE
Not functioning on the second monitor

### ISSUE THREAD

**Issue by joezhouchenye** [l3nn4rt/click-to-close-overview#4]
Cannot close the overview by clicking on the second monitor.

**Comment by l3nn4rt** [comment]
This is strange. The latest works just fine on gnome 45.

What GNOME version?
What extension version?
X11 or Wayland?

Did you try disabling all the extensions but this and restarting the shell?

**Comment by joezhouchenye** [comment]
I was using this on my older computer with GNOME 42. I just switched to a new laptop with GNOME 45 without any problem. Sorry for not giving enough information.
