### ISSUE TITLE
click on empty space in overview to show desktop

### ISSUE THREAD

**Issue by ardnod** [l3nn4rt/click-to-close-overview#5]
only this.
to add

**Comment by l3nn4rt** [comment]
I think this is what the extension already does.
Can you provide more info about what you expect, please?

**Comment by ardnod** [comment]
I meant this behaviour (videoedit):

Clickable area for this effect could be in the center, on the free space on the background view of wallpaper.
Click on desktop background hides all windows for a while, when I open something from desktop (e.g. folder, text file) everything are restoring.
Now I think it's not a good idea and default behaviour is OK.
I can switch desktop to see desktop icons and... this idea is not "according to the philosophy of GNOME" (in my opinion).
If You think what I think You can close this topic.

https://github.com/user-attachments/assets/d29d5b6e-c6b1-475b-b98f-caa8dd51fdbb

**Comment by ardnod** [comment]
You may delete this topic (I want)
