### ISSUE TITLE
Add support for GNOME 47

### ISSUE THREAD

**Issue by antrmn** [l3nn4rt/click-to-close-overview#7]
GNOME 47.rc has been released, with the stable release set for September 18. Please update for GNOME 47 compatibility. The upgrade guide can be found here: [Port Extensions to GNOME Shell 47](https://gjs.guide/extensions/upgrading/gnome-shell-47.html)

Thanks!

**Comment by martineztherock** [comment]
1. Download the file "click-to-close-overviewl3nn4rt.github.io.v11.shell-extension.zip".
2. Extract it anywhere (I used Downloads folder).
3. Rename the extracted folder to: "click-to-close-overview@l3nn4rt.github.io"
4. Inside the folder, edit the "metadata.json" file with any text editor and add a comma after "46", in a new line enter "47", like this and save the file...
  "shell-version": [
    "45",
    "46",
    "47"
  ],
5. Move the folder to: ~/.local/share/gnome-shell/extensions/
6. Logout and back in if you're using Wayland or Alt + F2, r, [ENTER] if on Xorg.
7. Enable the extension in the Extensions app.

**Comment by l3nn4rt** [comment]
I was away from my laptop recently and could not test it, sorry.
Just released - it should upgrade automatically via EGO soon.

Thank you!
